### ISSUE TITLE
`sanitize_filename` isnt called in `get_file()`

### ISSUE THREAD

**Issue by tHoMaStHeThErMoNuClEaRbOmB** [bczsalba/teahaz.py#1]
There could well be a logical reason for this but I want to make sure that you are aware that its not called and could lead to more injection vulnerabilities. :slightly_smiling_face:

**Comment by bczsalba** [comment]
Thanks for that, it's not called because `get_file()` doesn't actually write to a file, it only returns the data.

In the future there might be a `write_file()` method, but for now there is no place to put the call.

🚀
